[package]
name = "advent2023"
version = "0.1.0"
edition = "2021"
license = "Unlicense OR MIT"
authors = ["Grant Gurvis"]

[dependencies]
aho-corasick = "1.1.2"
reqwest = "0.11.22"
tokio = { version = "1.34.0", features = ["full"] }
