[alias]
t19 = "nextest run -E test(~2021)"
t20 = "nextest run -E test(~2021)"
t21 = "nextest run -E test(~2021)"
t22 = "nextest run -E test(~2022)"
t23 = "nextest run -E test(~2023)"
t24 = "nextest run -E test(~2024)"
t25 = "nextest run -E test(~2025)"
t26 = "nextest run -E test(~2026)"
t27 = "nextest run -E test(~2027)"
